### PR TITLE
Very basic debug printing

### PR DESCRIPTION
**Pull request by felixjones**
I think anything beyond this would need a string formatting library, and I'm not quite prepared to do that for the GBA just yet
```cpp
#include <gba/gba.hpp>

int main() {
    using namespace gba;

    log::init(log::mgba, log::nocash); // Try initialising logging for mGBA, and then no$gba
    log::print(log::level::info, "Hello, World!"); // Print "Hello, World!"
}
```
I've got my eyes on AGBPrint, but the source code out there is a bit funky, so I think I need to understand that API a bit better.

### CODE REVIEW

**Comment by JoaoBaptMG** [comment]
There might be a way to do a small `sprintf`-like library in compile time using C++20, saving the "intermediate" strings in ROM and computing a "method" of doing it. Might be a nightmare to pull off, though.

Otherwise, a basic `sprintf` implementation that uses varargs shouldn't be hard to pull off.

**Comment by felixjones** [comment]
Yes I thought of doing this compile time "compile the format" approach, it's definitely what I want to do

I think that would have uses beyond just debug printing

**Comment by JoaoBaptMG** [comment]
I saw this: https://github.com/SephDB/constexpr-format

In my own implementation ([StringBuilder](https://github.com/JoaoBaptMG/gba-modern/blob/master/source/text/StringBuilder.hpp) and [mGBADebugging](https://github.com/JoaoBaptMG/gba-modern/blob/master/source/text/mGBADebugging.hpp)), I forgo format strings and just append the parameters à la `iostream`, it might be a good start.

**Comment by felixjones** [comment]
Ooooooh that link looks like a good read. Thanks loads!

**Pull request closed without merging**
