### PR TITLE
Add meson.build

### PR DESCRIPTION
**Pull request by felixjones**

### CODE REVIEW

**Comment by LunarLambda** [comment]
looks good to me

**Comment by JoaoBaptMG** [comment]
Wait, how do you declare a "toolchain" in Meson? How do you state that the project should be compiled for the GBA instead of the host platform?

**Comment by felixjones** [comment]
That's the neat part: you don't
It's a header only library so toolchain is unnecessary, it's up to the user to figure all the platform specifics out

**Comment by JoaoBaptMG** [comment]
Oof! I should know better the projects I’m commenting to. I was talking about gba-toolchain 😅

**Comment by LunarLambda** [comment]
The closest thing to a cmake toolchain file that meson has is a 'cross file', a `.ini` style file that declares which programs and paths to use, as well as some options like the default compiler arguments. 

https://github.com/LunarLambda/meson-gba/blob/main/gba.ini

**Comment by JoaoBaptMG** [comment]
That’s interesting! That’s actually more organised that the tool chain support for CMake.

**Pull request merged**
